POST https://pure-sea-49895.herokuapp.com/api/emails/contact
Content-Type: application/json

{
    "fullName" : "Toni Gashi",
    "email": "lazaronshyta@gmail.com",
    "message": "I am toni testing"
}
